#!/bin/bash
# Updates /docs/reference/cli.md from the locally installed go-ipfs.
# TODO: Structure this around command groups (dag, object, files, etc.) 

exec &> ./cli.md

echo "---
title: \"Command-line reference\"
description: API documentation for the Go-IPFS command-line executable.
---

# Command-line

<!-- DO NOT EDIT THIS FILE. This file is auto-generated from \`generate-cli-docs.sh\`. Any changes you make to this file will be overwritten. To edit this file, change the contents of the \`generate-cli-docs.sh\` script. -->

IPFS can run in either _online_ or _offline_ mode. Online mode is when when you have IPFS running separately as a daemon process. If you do not have an IPFS daemon running, you are in offline mode. Some commands, like \`ipfs swarm peers\`, are only supported when online. The [command-line quickstart guide](../how-to/command-line-quick-start/#take-your-node-online) explains how to start the IPFS daemon and take your node online.

"

echo "_Generated on $(date +"%Y-%m-%d %T"), from go-ipfs $(ipfs version -n)._"
printf "\n"
ipfs commands | while read line ; do
  printf "## $line\n\n\`\`\`\n"
  $line --help
  printf "\`\`\`\n\n"
done
