name: markdownlint check

on: [pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.jsonc
      